## Create islands JSON

In [7]:
import pandas as pd
islands_table = pd.read_csv('tables/islands.csv', sep=';')
islands_table.reset_index(inplace=True, drop=True)

In [8]:
islands_table.to_json(r'islands.json', orient='index', force_ascii=False)
islands_table

,nameEn,nameGer,waters,areaInKm2,state,filename
0,Alexander Island,Alexander-I.-Insel,Bellingshausensee,49.070,kein (Antarktis),Alexander_Island.svg
1,Axel Heiberg Island,Axel Heiberg Island,Arktischer Ozean,43.178,Kanada,Axel_Heiberg_Island.svg
2,Baffin Island,Baffininsel,Nordatlantik/Arktischer Ozean,507.451,Kanada,Baffin_Island.svg
3,Bali,Bali,Indischer Ozean,5.561,Indonesien,Bali.svg
4,Banks Island,Banksinsel,Arktischer Ozean,70.028,Kanada,Banks_Island.svg
...,...,...,...,...,...,...
63,Tenerife,Teneriffa,Atlantischer Ozean,2.034,Spanien,Tenerife.svg
64,Tierra del Fuego,Feuerland,Südatlantik,47.992,Argentinien/Chile,Tierra_Fuego.svg
65,Timor,Timor,Indischer Ozean,28.418,Indonesien/Osttimor,Timor.svg
66,Vancouver Island,Vancouver Island,Pazifischer Ozean,31.285,Kanada,Vancouver_Island.svg
67,Victoria Island,Victoria-Insel,Arktischer Ozean,217.291,Kanada,Victoria_Island.svg